### ISSUE TITLE
Bug: Re-benchmark every pallet in runtime

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#203]
As noted by @apopiak here: https://github.com/galacticcouncil/HydraDX-node/pull/188#discussion_r610595114 we should re-weight every pallet in our runtime (with our settings) and use that instead of default.

**Comment by apopiak** [comment]
Just saw that Kusama also uses default weights in some places. So I guess you don't have to literally re-weight everything (that was just my gut reaction), but *check* all the pallets on whether they need to be weighted.

Re-weighting all of them is just the safe default. If you are confident that the benchmark will give the same result (because you use the same config on the same benchmarking hardware) you can skip it of course.

**Comment by jak-pan** [comment]
> Just saw that Kusama also uses default weights in some places. So I guess you don't have to literally re-weight everything (that was just my gut reaction), but _check_ all the pallets on whether they need to be weighted.
> 
> Re-weighting all of them is just the safe default. If you are confident that the benchmark will give the same result (because you use the same config on the same benchmarking hardware) you can skip it of course.

It's not that much work / time to do all of them on top of existing benchmarks so we might just add everything to be safe.

**Comment by jak-pan** [comment]
Also I've noticed that every transaction currently costs the same amount to execute. We should have a look at why this happens since exchange:buy should be more expensive than balance transfers

**Comment by jak-pan** [comment]
We should have a look here https://github.com/paritytech/polkadot/blob/5b755428f73345c0015d499482c48c37ce7b9e21/runtime/polkadot/src/constants.rs#L57
